In [1]:
import numpy as np

In [2]:
a = np.array([5,15,25,35,40,45,50,55,60,65,70])
print(a.size)
print(a.ndim)
print(a.shape)
print(a[2])

11
1
(11,)
25


In [3]:
m = np.array([[1,2,3],[4,5,6]])
#aficher 5
print(m[1,1])
#afficher la premiere ligne
print(m[0])
#afficher 2 eme collonne 
print(m[:,1])


5
[1 2 3]
[2 5]


In [4]:
#creer un tableau de 10 zeros 1D
np.zeros(10)
#creer une matrice 2*3
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
#creer un tableau de zero a 20 pas 4
np.arange(0, 21, 4)





array([ 0,  4,  8, 12, 16, 20])

In [6]:
a = np.array([10,25,30,45,50])
#afficher les elements >30
print(a[a>30])
#moyenne
print(a.mean())
#multiplier tous *3 operation vectorise
print(a*3)

[45 50]
32.0
[ 30  75  90 135 150]


In [7]:
y = np.array([1,2,3,4,5,6,7,8,9])
#transformer y en 3*3
y.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
table = np.array([2,4,6,8,10])
print(table.size)
print(table.ndim)
#afficher derniere element du tableau 
print(table[-1])

5
1
10


In [9]:
a = np.array([[7,8],[9,10]])
print(a[0,1])
print(a[::])
print(a[:0])

8
[[ 7  8]
 [ 9 10]]
[]


In [10]:
#un tableau de 1 element
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
#creer une matrice 3*2 remplit par 5
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [12]:
#creer un tableau de 1 a 10 le dernier element est exclut
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a = np.array([3,6,9,12])
#a>=6
print(a[a>=6])
print(a.sum())
print(a/3)

[ 6  9 12]
30
[1. 2. 3. 4.]


In [14]:
#transformer [1,2,3,4]
b = np.array([1,2,3,4])
print(a.reshape(2,2))
#creer matrice didentite 3*3
np.eye(3,3)




[[ 3  6]
 [ 9 12]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#creer un tableau de 1 a 10 le dernier element tjr exclut
a = np.arange(1,11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [16]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
np.full((3,4),1)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#table 2*3 remplit par7
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [20]:
#matrice identite 4*4
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
b = np.array([[1,2,3],[4,5,6]])
#tjr si on met print cela veut dre que ls resultats de tous les lignes seront affiche
#par contre si je met just b.size dans ce cas le resultat de dernier element uniquement qui sra affiche
print(b.size)
print(b.shape)
print(b.ndim)


6
(2, 3)
2


In [22]:
b[0]

array([1, 2, 3])

In [23]:
#afficher les deux premieres elements du tableau 
b[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
#dernier colonne de la matrice
b[:,-1]

array([3, 6])

In [25]:
a = np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
#ajouter 5 a chaque element
a+5

array([ 6,  7,  8,  9, 10, 11])

In [27]:
#calculerdeux tableau elements pr elements faut qu ils soient de memee taillee
b = np.array([2,4,6,8,10,12])
a*b

array([ 2,  8, 18, 32, 50, 72])

In [28]:
print(a.sum())
print(a.mean())
print(a.min())
print(a.max())


21
3.5
1
6


In [29]:
print(b.sum())
print(b.mean())
print(b.min())
print(b.max())


42
7.0
2
12


In [30]:
b[a>10]

array([], dtype=int64)