# NumPy Practice – Slicing & Fancy Indexing

Ce notebook contient des exercices pratiques dédiés à la manipulation
avancée des tableaux NumPy, en mettant l’accent sur :

- Slicing (extraction de sous-tableaux)
- Fancy indexing (sélection par indices multiples)
- Boolean indexing (sélection conditionnelle)
- Cas pratiques fréquemment utilisés en Data Science

Objectif : comprendre et maîtriser les différentes techniques
d’indexation de NumPy à travers des exemples concrets et progressifs.


In [22]:
import numpy as np 

In [25]:
#creation de table numpy contennat ds nbrs de 1 a 25 et de taille 5*5
table = np.arange(1,26).reshape(5,5)
print(table)
#np.arange pour creer les donnees
#np.reshape c pour changer  la forme dun tableau deja existant 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [26]:
#extraire la troisieme ligne de tablea 
table[2,:]
#cela veut dire troisieme ligne et tous les collonne ; on peut aussi lextraire de cette formee: table[2] c la meme chose 

array([11, 12, 13, 14, 15])

In [27]:
#extraire la deuxieme collonne 
table[:,1]
# le : veut dire tous les lignes et 1 c la deuxieme collonne

array([ 2,  7, 12, 17, 22])

In [28]:
#extraire une sous matrices 3*3 situe en haut a gauche
table[:3,:3]
#:3 debut c 0 et la fin c 3 qui est non inclut donc resultat ligne 0,1,2 
#:3 pour colonne 0 le debut; et 3 c la fin donc resultat colonne 0,1,2
#c comme prendre les trois premiere ligne et les trois premieres collonnes

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [29]:
#extraire une ligne sur 2 et une colonne sur 2
table[::2,::2]
#::2 cad [debut,fin,pas] donc ::2 cad pas 2 
#donc les indices seront 0 2 4 6... 
#lorsqu on dis sur 2 ca veut dire pas la devision mais plutot c le pas :combien de ligne ou collonne on saut avant de prendre la suivante
#pas 2 on prend le premiere , on saut le deuxieme etc

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [30]:
#extraire la premiere et la 5 eme ligne de tableau
table[[0,4],:]
# ici fancy indexing permet de manipuler une liste dindices dans ce cas indice 0 et 4;

array([[ 1,  2,  3,  4,  5],
       [21, 22, 23, 24, 25]])

In [31]:
#extraire la deuxieme et la 4 eme colonnes
#fancy indexing
table[:,[1,3]]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24]])

In [32]:
#extraire les elemnts situer aux position;(1,1),(3,3)
table[[1,3],[1,3]]

array([ 7, 19])

In [33]:
#affciher tous ls elements >15
#la condition creer un masque booleaan
#masuqe boolean c un tableau de true &false correspond a la condition de tableau
#retourne true  si lelemnt est selectionnee & false si il es ignorer
#les valeurs qui ne verifie pas la condition vaut false et celle qui verifier la conditiion:>15 vaut true 
table[table>15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25])

In [39]:
#remplacer tous les elemnt inferieur a 10 par 0
table[table<10] = 0
# = cad affectation
# == comparison 
print(table)

[[ 0  0  0  0  0]
 [ 0  0  0  0 10]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


In [40]:
#remplacer tous les elemnts paire par superieur a 10 par 1
x = (table%2==0) & (table>10)
table[x]=1
#on peut la faire de cette maniere
#table[(table%2==0) & (table>10)] = 1


[[ 0  0  0  0  0]
 [ 0  0  0  0 10]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


In [20]:
#inverser tous les lignes & colonne de tableau 
table[::-1,::-1]
#::-1 iverse lordre ds indices


array([[25,  1, 23,  1, 21],
       [ 1, 19,  1, 17,  1],
       [15,  1, 13,  1, 11],
       [10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0]])

In [21]:
#inverser uniquemnt ls collones de tableau
table[:,::-1]

array([[ 0,  0,  0,  0,  0],
       [10,  0,  0,  0,  0],
       [15,  1, 13,  1, 11],
       [ 1, 19,  1, 17,  1],
       [25,  1, 23,  1, 21]])

# Conclusion
Dans ce notebook, j’ai appris et pratiqué :
- Le slicing pour extraire des sous-parties d’un tableau
- Le fancy indexing pour sélectionner des lignes/colonnes spécifiques
- Le boolean indexing pour filtrer ou modifier des éléments selon une condition
Ces compétences sont très utiles en Data Science pour manipuler rapidement des tableaux NumPy.
