# TP NumPy – Exercice 2

Ce notebook présente des exercices pratiques pour apprendre NumPy :
- manipulation de tableaux
- slicing et fancy indexing
- boolean indexing
- statistiques (min, max, mean, sum)
- normalisation
- tableaux 3D et reshape

In [25]:
import numpy as np

In [26]:
#creation dun tableau x contennat ds nbr de 10 a 50
x = np.arange(10,51)

In [27]:
#creation d un table 3*3 remplit de nbr aleatoir entre 10 et 50
#randint nbr aleatoir entre 10 et 50
#size(3,3) 3*3
x = np.random.randint(10,51,size=(3,3))

In [28]:
#remplacer tous ls nbrs paires par 0
#%2==0 pour detecter les nbrs paires
x[x%2==0] = 0
print(x)

[[ 0 43  0]
 [11  0 25]
 [ 0  0  0]]


In [29]:
#afficher lelemnt situer a la deuxieme ligne colonne 3
#2 eme ligne index 1  && 3 eme collonne indice 2
print(x[1, 2])


25


In [30]:
#slicing
#extraire premiere ligne
a = x[0,:]
#extraire derniere colonne 
b = x[:,-1]
print(a,b)

[ 0 43  0] [ 0 25  0]


In [31]:
#fancy indexing
#extraire les deux premier ligne et les deux premiere collonnes
x[:2,:2]
#:2 pour ligne :  commence de  ligne 0 2 arrete avant ligne 2 donc lign 0 et 1 deux premiere ligne
#:2 pour colonne ; commence de collone 0 arrete avant colonne 2 donc collonne 0 1 les deux premiere colonne



array([[ 0, 43],
       [11,  0]], dtype=int32)

In [32]:
#fancy indexing
#extraire ls elements:1ere et 3 eme ligne ;1 ere et 3 eme colonne
x[[0,2],:] [:,[0,2]]

    

array([[0, 0],
       [0, 0]], dtype=int32)

In [33]:
#boolean indexing
#afficher tous ls elemnts superieur a 30
x[x>30]


array([43], dtype=int32)

In [34]:
#boolean indexing
#remplacer tous ls elemtns inferieur a 20 par 20
x[x<20] = 20
print(x)

[[20 43 20]
 [20 20 25]
 [20 20 20]]


In [35]:
#statistiques
#calculer la somme de chaque ligne et chaque collonne
#axis=1 veut dire horizzental veut dire ligne 
#sxis=0 cad vertical cas colonne
xl= x.sum(axis=1)
xc= x.sum(axis=0)
print(xl,xc)
#axis=1 ligne
#axis=0 colonne

[83 65 60] [60 83 65]


In [40]:
#statistique
#calculer min max moyenne de tableau
print(x.sum())
print(x.min())
print(x.max())
print(x.mean())

208
20
43
23.11111111111111


In [41]:
#statistiques
#calculer moyenn,min,max de chaque collonne et chaaque ligne

x.min(axis=1) , x.max(axis=1) , x.mean(axis=1)
#calculer moyenn,min,max de chaque collone
x.max(axis=0) , x.min(axis=0) , x.mean(axis=0)





(array([20, 43, 25], dtype=int32),
 array([20, 20, 20], dtype=int32),
 array([20.        , 27.66666667, 21.66666667]))

In [42]:
#normalisation
#normaliser le tableau
#x.mean() pour calculler moyennn ;x.std calcul d ecart type et x-x.mean()/x.std pour centrer et reduit les valeur
#x-x.mean() la soustraction de moyenne cad le centre devien 0 ;  on devise par lecart type la variance devien 1 
x_normalise = (x-x.mean() /x.std())

In [43]:
#creer un table 3D avec un loi normal
x3d = np.random.randn(3,3,3)

In [44]:
#transformer ce tableau en vecteur 1D de taille 27 
x1D = x3d.reshape(27)
print(x3d)

[[[ 1.02175934  0.49339917 -0.71787187]
  [-0.85596236  0.8845037   0.51874828]
  [-0.73435878 -0.45567575  0.25746099]]

 [[-0.5674261   0.91573991  0.01660534]
  [-2.04023166 -0.85595484  0.02785892]
  [ 0.64803195  0.96449715 -0.08368227]]

 [[ 0.89479739  0.73301157  1.95422566]
  [-1.52415608 -0.72653565  1.59554622]
  [ 0.33478254 -1.15035612 -0.33034663]]]


In [45]:
#souvegard le tableau dans un fichier .npy et le relire
np.save("tableau.npy",x3d)
np_xloaded = np.load("tableau.npy")